services:
  - type: web
    name: rehablo-api
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.14.0

